---
title: "Gov 50 Final Project"
author: Hanna Johnson
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to the role of women in politics, parricularly whether or not the existence of an office or position dedicated to the advancement of women's rights in the government is correlated with a higher percentage of "female-friendly" policies.  I am currently unsure how to define "female-friendly" policies, but they will likely be policies that primarily effect women (i.e. domestic/sexual violence, women's rights to do something like voting or driving, the menstrual cycles, maternity leave and protections of mothers during pregnancy and after birth, accessibility to affordable and safe birth control, legal right to an abortion, etc).  I am also interested in looking at the existence of these agencies to see if they lead to a a decrease in crimes against women or a more positive perception of women's competence and a decrease in both subtle and classic sexism.
